#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-pecanwsme
Version  : 0.8.0
Release  : 12
URL      : https://pypi.python.org/packages/source/s/sphinxcontrib-pecanwsme/sphinxcontrib-pecanwsme-0.8.0.tar.gz
Source0  : https://pypi.python.org/packages/source/s/sphinxcontrib-pecanwsme/sphinxcontrib-pecanwsme-0.8.0.tar.gz
Summary  : Extension to Sphinx for documenting APIs built with Pecan and WSME
Group    : Development/Tools
License  : Apache-2.0
Requires: sphinxcontrib-pecanwsme-python
BuildRequires : pbr
BuildRequires : pbr-python
BuildRequires : pip
BuildRequires : pip-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
sphinxcontrib-pecanwsme
=======================
Extension to Sphinx for documenting APIs built with Pecan and WSME

%package python
Summary: python components for the sphinxcontrib-pecanwsme package.
Group: Default

%description python
python components for the sphinxcontrib-pecanwsme package.


%prep
%setup -q -n sphinxcontrib-pecanwsme-0.8.0

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
